public class ProdDemoController {
	//Added method
	public String getUserName(){
		return UserInfo.getUserName();
	}
	
	//Method
    public PageReference seeresult() {
        return null;
    }

	
    public String l { get; set; }

    public String tobacconicotineuse { get; set; }

    public String yearOptions { get; set; }

    public String yearofbirth { get; set; }

    public String monthOptions { get; set; }

    public String monthofbirth { get; set; }

    public String openPresentationOptions { get; set; }

    

    Public String DateofBirth{get;set;}
    Public String model{get;set;}
    Public Integer type{get;set;}
    Public String Budget{get;set;}
       Public String Loan{get;set;}
    Public String State{get;set;}
    Public String City{get;set;}
    Public Integer FormatType{get;set;}
    Public ProdDemoController(){
        
    }
    Public Void FindDealer(){
        
    }
}